CRYPTO_LIB = mbedtls/

VPATH += :$(FIRMWAREPATH)/crypto/$(CRYPTO_LIB)/library
EXTRAINCDIRS += $(FIRMWAREPATH)/crypto/$(CRYPTO_LIB)/include

ifeq ($(CRYPTO_OPTIONS),AES128C)
 SRC += aes-independant.c

 #######
 #*This is the recommended first version to test* 
 SRC += aes.c platform_util.c
 CDEFS += -DMBEDTLS -DMBEDTLS_SHA1_C
 
 ifeq ($(MBEDTLS_AES_ROM_TABLES),)
 else
 CDEFS += -DMBEDTLS_AES_ROM_TABLES=$(MBEDTLS_AES_ROM_TABLES)
 endif
 
else ifeq ($(CRYPTO_OPTIONS),RSA)
 SRC += rsa.c bignum.c md.c md5.c sha1.c sha256.c sha512.c ripemd160.c oid.c platform_util.c
 CDEFS += -DMBEDTLS -DMBEDTLS_SHA
    
else ifeq ($(CRYPTO_OPTIONS),ECDSA)
 SRC += ecdsa.c ecp.c ecp_curves.c bignum.c error.c  platform_util.c  platform.c  hmac_drbg.c md.c sha256.c sha512.c 
 CDEFS += -DMBEDTLS -DMBEDTLS_SHA

#else ifeq ($(CRYPTO_OPTIONS),ECDSA)
# SRC += ecdsa.c ecp.c ecp_curves.c bignum.c md.c md5.c sha1.c sha256.c sha512.c ripemd160.c error.c hmac_drbg.c  platform_util.c  platform.c memory_buffer_alloc.c
# CDEFS += -DMBEDTLS -DMBEDTLS_SHA 

    
else ifeq ($(CRYPTO_OPTIONS),SHA1)
 SRC += sha1.c platform_util.c
 CDEFS += -DMBEDTLS -DMBEDTLS_SHA
    
else

 $(error: Unknown or blank CRYPTO_OPTIONS: $(CRYPTO_OPTIONS). CRYPTO_OPTIONS is required for this CRYPTO_TARGET)
endif #AVRCRYPTOLIB


